return {
  Github = '  ',
  Stack = '  ',
  Buffer = '  ',
  Bomb = '  ',

  Success = '✓',
  Failure = '✗',
  Pending = '➜',

  Search = '  ',
  File = '  ',
  Files = '  ',
  Settings = '  ',
  CloseCircle = '  ',
  Register = '  ',

  -- Lsp kinds
  Snippet = '  ',
  FolderOpen = '  ',
  Terminal = '  ',
  Text = '  ',
  Method = ' ƒ ',
  Function = ' ƒ ',
  Constructor = '  ',
  Variable = '  ',
  Class = '  ',
  Interface = ' ﰮ ',
  Module = '  ',
  Property = '  ',
  Unit = '  ',
  Value = '  ',
  Enum = ' 了 ',
  Keyword = '  ',
  Color = '  ',
  Folder = '  ',
  EnumMember = '  ',
  Constant = '  ',
  Struct = '  ',
  Reference = '  ',
  Field = '  ',
  Operator = '  ',
  Copilot = '  ',
}
