local colors = require('theme.colors')

local config = {
  TelescopeResultsTitle = { fg = colors.green },
  TelescopePromptTitle = { fg = colors.blue },
  TelescopePreviewTitle = { fg = colors.purple },
  TelescopeResultsBorder = { fg = colors.light0 },
  TelescopePromptBorder = { fg = colors.light0 },
  TelescopePreviewBorder = { fg = colors.light0 },
  TelescopeSelectionCaret = { fg = colors.red },
  TelescopeMatching = { fg = colors.yellow },
  TelescopeSelection = { bg = colors.grey },
  TelescopeMultiSelection = { fg = colors.blue },
  TelescopeMultiIcon = { fg = colors.blue },
  TelescopeNormal = { fg = colors.light0, bg = colors.dark0 },
  TelescopePreviewNormal = { fg = colors.light0, bg = colors.dark0 },
  TelescopePromptNormal = { fg = colors.light0, bg = colors.dark0 },
  TelescopeResultsNormal = { fg = colors.light0, bg = colors.dark0 },
  TelescopeBorder = { fg = colors.light0 },
  TelescopeTitle = { fg = colors.light0 },
  TelescopePromptCounter = { fg = colors.grey },
  TelescopePromptPrefix = { fg = colors.blue },
  TelescopePreviewLine = { bg = colors.grey },
  TelescopePreviewMatch = { fg = colors.yellow },
  TelescopePreviewPipe = { fg = colors.yellow },
  TelescopePreviewCharDev = { fg = colors.yellow },
  TelescopePreviewDirectory = { fg = colors.blue },
  TelescopePreviewBlock = { fg = colors.yellow },
  TelescopePreviewLink = { fg = colors.blue },
  TelescopePreviewSocket = { fg = colors.purple },
  TelescopePreviewRead = { fg = colors.yellow },
  TelescopePreviewWrite = { fg = colors.purple },
  TelescopePreviewExecute = { fg = colors.green },
  TelescopePreviewHyphen = { fg = colors.grey },
  TelescopePreviewSticky = { fg = colors.blue },
  TelescopePreviewSize = { fg = colors.green },
  TelescopePreviewUser = { fg = colors.yellow },
  TelescopePreviewGroup = { fg = colors.yellow },
  TelescopePreviewDate = { fg = colors.blue },
  TelescopePreviewMessage = { fg = colors.light0 },
  TelescopePreviewMessageFillchar = { fg = colors.light0 },
  TelescopeResultsClass = { fg = colors.yellow },
  TelescopeResultsConstant = { fg = colors.yellow },
  TelescopeResultsField = { fg = colors.red },
  TelescopeResultsFunction = { fg = colors.blue },
  TelescopeResultsMethod = { fg = colors.blue },
  TelescopeResultsOperator = { fg = colors.aqua },
  TelescopeResultsStruct = { fg = colors.purple },
  TelescopeResultsVariable = { fg = colors.red },
  TelescopeResultsLineNr = { fg = colors.light1 },
  TelescopeResultsIdentifier = { fg = colors.blue },
  TelescopeResultsNumber = { fg = colors.orange },
  TelescopeResultsComment = { fg = colors.light3 },
  TelescopeResultsSpecialComment = { fg = colors.grey },
  TelescopeResultsDiffChange = { fg = colors.none, bg = colors.yellow },
  TelescopeResultsDiffAdd = { fg = colors.none, bg = colors.green },
  TelescopeResultsDiffDelete = { fg = colors.none, bg = colors.red },
  TelescopeResultsDiffUntracked = { fg = colors.none, bg = colors.light4 },
}

return config
